campain:
  version:            '1.0'
  description:         Notebook test on CPU, default settings.
  directory:          ./campains/cpu-default
  existing_notebook:  'skip'      # remove|skip
  report_template:    'fidle'     # fidle|default
  timeout:            6000

  environment_vars:
    FIDLE_SAVE_FIGS:         true


#
# ------------ LinearReg
#
LINR1:
  notebook: LinearReg/01-Linear-Regression.ipynb

GRAD1:
  notebook: LinearReg/02-Gradient-descent.ipynb

POLR1:
  notebook: LinearReg/03-Polynomial-Regression.ipynb

LOGR1:
  notebook: LinearReg/04-Logistic-Regression.ipynb

#
# ------------ Perceptron
#
PER57:
  notebook: Perceptron/01-Simple-Perceptron.ipynb

#
# ------------ BHPD.Keras3
#
K3BHPD1:
  notebook: BHPD.Keras3/01-DNN-Regression.ipynb
  overrides:
    fit_verbosity: 2

K3BHPD2:
  notebook: BHPD.Keras3/02-DNN-Regression-Premium.ipynb
  overrides:
    fit_verbosity: 2

#
# ------------ BHPD.PyTorch
#
PBHPD1:
  notebook: BHPD.PyTorch/01-DNN-Regression_PyTorch.ipynb

#
# ------------ Wine.Keras3
#
K3WINE1:
  notebook: Wine.Keras3/01-DNN-Wine-Regression.ipynb
  overrides:
    fit_verbosity: 2
    dataset_name: default

#
# ------------ Wine.Lightning
#
LWINE1:
  notebook: Wine.Lightning/01-DNN-Wine-Regression-lightning.ipynb
  overrides:
    fit_verbosity: 2
    dataset_name: default

#
# ------------ MNIST.Keras3
#
K3MNIST1:
  notebook: MNIST.Keras3/01-DNN-MNIST.ipynb
  overrides:
    fit_verbosity: 2

K3MNIST2:
  notebook: MNIST.Keras3/02-CNN-MNIST.ipynb
  overrides:
    fit_verbosity: 2

#
# ------------ MNIST.PyTorch
#
#PMNIST1:
#  notebook: MNIST.PyTorch/01-DNN-MNIST_PyTorch.ipynb

#
# ------------ MNIST.Lightning
#
#LMNIST2:
#  notebook: MNIST.Lightning/02-CNN-MNIST_Lightning.ipynb

#
# ------------ GTSRB.Keras3
#
K3GTSRB1:
  notebook: GTSRB.Keras3/01-Preparation-of-data.ipynb
  overrides:
    scale: default
    output_dir: default
    progress_verbosity: default

K3GTSRB2:
  notebook: GTSRB.Keras3/02-First-convolutions.ipynb
  after:    K3GTSRB1
  overrides:
    enhanced_dir: default
    dataset_name: default
    batch_size: default
    epochs: default
    scale: default
    fit_verbosity: 2

K3GTSRB3:
  notebook: GTSRB.Keras3/03-Better-convolutions.ipynb
  after:    K3GTSRB1
  overrides:
    enhanced_dir: default
    model_name: default
    dataset_name: default
    batch_size: default
    epochs: default
    scale: default
    fit_verbosity: 2

#
# ------------ Embedding.Keras3
#
K3IMDB1:
  notebook: Embedding.Keras3/01-One-hot-encoding.ipynb
  overrides:
    vocab_size: default
    hide_most_frequently: default
    batch_size: default
    epochs: default
    fit_verbosity: 2

K3IMDB2:
  notebook: Embedding.Keras3/02-Keras-embedding.ipynb
  overrides:
    vocab_size: default
    hide_most_frequently: default
    review_len: default
    dense_vector_size: default
    batch_size: default
    epochs: default
    output_dir: default
    fit_verbosity: 2

K3IMDB3:
  notebook: Embedding.Keras3/03-Prediction.ipynb
  after:    K3IMDB2
  overrides:
    vocab_size: default
    review_len: default
    saved_models: default
    dictionaries_dir: default

K3IMDB4:
  notebook: Embedding.Keras3/04-Show-vectors.ipynb
  after:    K3IMDB2
  overrides:
    vocab_size: default
    review_len: default
    saved_models: default
    dictionaries_dir: default

K3IMDB5:
  notebook: Embedding.Keras3/05-LSTM-Keras.ipynb
  overrides:
    vocab_size: default
    hide_most_frequently: default
    review_len: default
    dense_vector_size: default
    batch_size: default
    epochs: default
    fit_verbosity: 2
    scale: default

#
# ------------ RNN.Keras3
#
K3LADYB1:
  notebook: RNN.Keras3/01-Ladybug.ipynb
  overrides:
    scale: default
    train_prop: default
    sequence_len: default
    predict_len: default
    batch_size: default
    epochs: default

#
# ------------ AE.Keras3
#
K3AE1:
  notebook: AE.Keras3/01-Prepare-MNIST-dataset.ipynb
  overrides:
    prepared_dataset: default
    scale: 0.1
    progress_verbosity: default

K3AE2:
  notebook: AE.Keras3/02-AE-with-MNIST.ipynb
  after: K3AE1
  overrides:
    prepared_dataset: default
    dataset_seed: default
    scale: 1
    latent_dim: default
    train_prop: default
    batch_size: default
    epochs: 4
    fit_verbosity: default

K3AE3:
  notebook: AE.Keras3/03-AE-with-MNIST-post.ipynb
  after: K3AE2
  overrides:
    prepared_dataset: default
    dataset_seed: default
    scale: 1
    train_prop: default
    
K3AE4:
  notebook: AE.Keras3/04-ExtAE-with-MNIST.ipynb
  after: K3AE1
  overrides:
    prepared_dataset: default
    dataset_seed: default
    scale: 1
    train_prop: default
    batch_size: default
    epochs: 4
    fit_verbosity: default

K3AE5:
  notebook: AE.Keras3/05-ExtAE-with-MNIST.ipynb
  after: K3AE1
  overrides:
    prepared_dataset: default
    dataset_seed: default
    scale: 1
    train_prop: default
    batch_size: default
    epochs: 4
    fit_verbosity: default

#
# ------------ VAE.Keras3
#
K3VAE1:
  notebook: VAE.Keras3/01-VAE-with-MNIST-LossLayer.ipynb
  overrides:
    latent_dim: default
    loss_weights: default
    scale: 0.1
    seed: default
    batch_size: default
    epochs: 4
    fit_verbosity: default

K3VAE2:
  notebook: VAE.Keras3/02-VAE-with-MNIST.ipynb
  overrides:
    latent_dim: default
    loss_weights: default
    scale: 0.1
    seed: default
    batch_size: default
    epochs: 4
    fit_verbosity: default

K3VAE3:
  notebook: VAE.Keras3/03-VAE-with-MNIST-post.ipynb
  after: K3VAE2
  overrides:
    scale: 0.1
    seed: default
    models_dir: default

#
# ------------ DCGAN.Lightning
#
PLSHEEP3:
  notebook: DCGAN.Lightning/01-DCGAN-PL.ipynb
  overrides:
    latent_dim: default
    gan_name: GAN
    generator_name: default
    discriminator_name: default
    epochs: 4
    lr: default
    b1: default
    b2: default
    batch_size: default
    num_img: default
    fit_verbosity: default
    dataset_file: default
    data_shape: default
    scale: 0.001
    num_workers: default

PLSHEEP3:
  notebook: DCGAN.Lightning/01-DCGAN-PL.ipynb
  overrides:
    latent_dim: default
    gan_name: WGANGP
    generator_name: default
    discriminator_name: default
    epochs: 4
    lr: default
    b1: default
    b2: default
    batch_size: default
    num_img: default
    fit_verbosity: default
    dataset_file: default
    data_shape: default
    scale: 0.001
    num_workers: default



#
# ------------ Misc
#
NP1:
  notebook: Misc/00-Numpy.ipynb

ACTF1:
  notebook: Misc/01-Activation-Functions.ipynb

PANDAS1:
  notebook: Misc/02-Using-pandas.ipynb

FID1:
  notebook: Misc/07-Fid-Example.ipynb
  overrides:
    scale: .1
    x: 345
    batch_size: default