campain:
  version:           1.0
  description:       Complete validation of notebooks with default settings
  directory:         ./campains/default_settings
  existing_notebook: skip
  report_template:   fidle
  timeout:           6000
  environment_vars:
    FIDLE_SAVE_FIGS:         true
    TF_CPP_MIN_LOG_LEVEL:    2


#
# ------------ LinearReg
#
LINR1:
  notebook: LinearReg/01-Linear-Regression.ipynb

GRAD1:
  notebook: LinearReg/02-Gradient-descent.ipynb

POLR1:
  notebook: LinearReg/03-Polynomial-Regression.ipynb

LOGR1:
  notebook: LinearReg/04-Logistic-Regression.ipynb

#
# ------------ IRIS
#
PER57:
  notebook: IRIS/01-Simple-Perceptron.ipynb

#
# ------------ BHPD
#
BHPD1:
  notebook: BHPD/01-DNN-Regression.ipynb
  overrides:
    fit_verbosity: 2

BHPD2:
  notebook: BHPD/02-DNN-Regression-Premium.ipynb
  overrides:
    fit_verbosity: 2

WINE1:
  notebook: BHPD/03-DNN-Wine-Regression.ipynb
  overrides:
    fit_verbosity: 2
    dataset_name: default
#
# ------------ MNIST
#
MNIST1:
  notebook: MNIST/01-DNN-MNIST.ipynb
  overrides:
    fit_verbosity: 2

MNIST2:
  notebook: MNIST/02-CNN-MNIST.ipynb
  overrides:
    fit_verbosity: 2

#
# ------------ GTSRB
#
GTSRB1:
  notebook:      GTSRB/01-Preparation-of-data.ipynb
  overrides:
    scale:                 default
    output_dir:            default
    progress_verbosity:    2

GTSRB2:
  notebook:      GTSRB/02-First-convolutions.ipynb
  after:         GTSRB1
  overrides:
    enhanced_dir:          default
    dataset_name:          default
    batch_size:            default
    epochs:                default
    scale:                 default
    fit_verbosity:         2

GTSRB3:
  notebook:      GTSRB/03-Tracking-and-visualizing.ipynb
  after:         GTSRB1
  overrides:
    enhanced_dir:          default
    dataset_name:          default
    batch_size:            default
    epochs:                default
    scale:                 default
    fit_verbosity:         2

GTSRB4:
  notebook:      GTSRB/04-Data-augmentation.ipynb
  after:         GTSRB1
  overrides:
    enhanced_dir:          default
    dataset_name:          default
    batch_size:            default
    epochs:                default
    scale:                 default
    fit_verbosity:         2

GTSRB5:
  notebook:      GTSRB/05-Full-convolutions.ipynb
  after:         GTSRB1
  overrides:
    enhanced_dir:          default
    datasets:              default
    models:                default
    batch_size:            default
    epochs:                default
    scale:                 default
    with_datagen:          default
    fit_verbosity:         2

GTSRB6:
  notebook:      GTSRB/06-Notebook-as-a-batch.ipynb

GTSRB7:
  notebook:      GTSRB/07-Show-report.ipynb
  after:         GTSRB5
  overrides:
    report_dir:            default

#
# ------------ IMDB
#
IMDB1:
  notebook:      IMDB/01-One-hot-encoding.ipynb
  overrides:
    vocab_size:            default
    hide_most_frequently:  default
    batch_size:            default
    epochs:                default
    fit_verbosity:         2

IMDB2:
  notebook:      IMDB/02-Keras-embedding.ipynb
  overrides:
    vocab_size:            default
    hide_most_frequently:  default
    review_len:            default
    dense_vector_size:     default
    batch_size:            default
    epochs:                default
    output_dir:            default
    fit_verbosity:         2

IMDB3:
  notebook:      IMDB/03-Prediction.ipynb
  after:         IMDB2
  overrides:
    vocab_size:            default
    review_len:            default
    saved_models:          default
    dictionaries_dir:      default

IMDB4:
  notebook:      IMDB/04-Show-vectors.ipynb
  after:         IMDB2
  overrides:
    vocab_size:            default
    review_len:            default
    saved_models:          default
    dictionaries_dir:      default

IMDB5:
  notebook:      IMDB/05-LSTM-Keras.ipynb
  overrides:
    vocab_size:            default
    hide_most_frequently:  default
    review_len:            default
    dense_vector_size:     default
    batch_size:            default
    epochs:                default
    scale:                 default
    fit_verbosity:         2

#
# ------------ SYNOP
#
LADYB1:
  notebook:      SYNOP/LADYB1-Ladybug.ipynb
  overrides:
    scale:                 default
    train_prop:            default
    sequence_len:          default
    predict_len:           default
    batch_size:            default
    epochs:                default

SYNOP1:
  notebook:      SYNOP/SYNOP1-Preparation-of-data.ipynb
  overrides:
    output_dir:            default

SYNOP2:
  notebook:      SYNOP/SYNOP2-First-predictions.ipynb
  after:         SYNOP1
  overrides:
    scale:                 default
    train_prop:            default
    sequence_len:          default
    batch_size:            default
    epochs:                default
    fit_verbosity:         2

SYNOP3:
  notebook:      SYNOP/SYNOP3-12h-predictions.ipynb
  after:         SYNOP2
  overrides:
    iterations:            default
    scale:                 default
    train_prop:            default
    sequence_len:          default

#
# ------------ Transformers
#
# TRANS1:
#   notebook:      Transformers/01-Distilbert.ipynb
#
# TRANS2:
#   notebook:      Transformers/02-distilbert_colab.ipynb

#
# ------------ AE
#
AE1:
  notebook:      AE/01-Prepare-MNIST-dataset.ipynb
  overrides:
    prepared_dataset:      default
    scale:                 default
    progress_verbosity:    2

AE2:
  notebook:      AE/02-AE-with-MNIST.ipynb
  after:         AE1
  overrides:
    prepared_dataset:      default
    dataset_seed:          default
    scale:                 default
    latent_dim:            default
    train_prop:            default
    batch_size:            default
    epochs:                default
    fit_verbosity:         2

AE3:
  notebook:      AE/03-AE-with-MNIST-post.ipynb
  after:         AE2
  overrides:
    prepared_dataset:      default
    dataset_seed:          default
    scale:                 default
    train_prop:            default

AE4:
  notebook:      AE/04-ExtAE-with-MNIST.ipynb
  after:         AE1
  overrides:
    prepared_dataset:      default
    dataset_seed:          default
    scale:                 default
    latent_dim:            default
    train_prop:            default
    batch_size:            default
    epochs:                default
    fit_verbosity:         2

AE5:
  notebook:      AE/05-ExtAE-with-MNIST.ipynb
  after:         AE1
  overrides:
    prepared_dataset:      default
    dataset_seed:          default
    scale:                 default
    latent_dim:            default
    train_prop:            default
    batch_size:            default
    epochs:                default
    fit_verbosity:         2

#
# ------------ VAE
#
VAE1:
  notebook:       VAE/01-VAE-with-MNIST.ipynb
  overrides:
    latent_dim:            default
    loss_weights:          default
    scale:                 default
    seed:                  default
    batch_size:            default
    epochs:                default
    fit_verbosity:         2

VAE2:
  notebook:       VAE/02-VAE-with-MNIST.ipynb
  overrides:
    latent_dim:            default
    loss_weights:          default
    scale:                 default
    seed:                  default
    batch_size:            default
    epochs:                default
    fit_verbosity:         2

VAE3:
  notebook:       VAE/03-VAE-with-MNIST-post.ipynb
  after:          VAE2
  overrides:
    scale:                 default
    seed:                  default
    models_dir:            default

VAE5:
  notebook:       VAE/05-About-CelebA.ipynb
  overrides:
    progress_verbosity:    2

VAE6.1:
  notebook:       VAE/06-Prepare-CelebA-datasets.ipynb
  overrides:
    scale:                 default
    seed:                  default
    cluster_size:          default
    image_size:            (128,128)
    output_dir:            default
    exit_if_exist:         default
    progress_verbosity:    2

VAE6.2:
  notebook:       VAE/06-Prepare-CelebA-datasets.ipynb
  overrides:
    scale:                 default
    seed:                  default
    cluster_size:          default
    image_size:            (192,160)
    output_dir:            default
    exit_if_exist:         default
    progress_verbosity:    2

VAE7:
  notebook:       VAE/07-Check-CelebA.ipynb
  after:          VAE6.1
  overrides:
    image_size:            default
    enhanced_dir:          default
    progress_verbosity:    2

VAE8:
  notebook:       VAE/08-VAE-with-CelebA-128x128.ipynb
  after:          VAE6.1
  overrides:
    scale:                 default
    image_size:            default
    enhanced_dir:          default
    latent_dim:            default
    loss_weights:          default
    batch_size:            default
    epochs:                default
    fit_verbosity:         2

VAE9:
  notebook:       VAE/09-VAE-with-CelebA-192x160.ipynb
  after:          VAE6.2
  overrides:
    scale:                 default
    image_size:            default
    enhanced_dir:          default
    latent_dim:            default
    loss_weights:          default
    batch_size:            default
    epochs:                default
    fit_verbosity:         2

VAE10.1:
  notebook:      VAE/10-VAE-with-CelebA-post.ipynb
  after:         VAE8
  overrides:
    image_size:            (128,128)
    enhanced_dir:          default
    models_dir:            ./run/VAE8

VAE10.2:
  notebook:      VAE/10-VAE-with-CelebA-post.ipynb
  after:         VAE9
  overrides:
    image_size:            (192,160)
    enhanced_dir:          default
    models_dir:            ./run/VAE9

#
# ------------ DCGAN
#
SHEEP1:
  notebook:      DCGAN/01-DCGAN-Draw-me-a-sheep.ipynb
  overrides:
    scale:                 default
    latent_dim:            default
    epochs:                default
    batch_size:            default
    num_img:               default
    fit_verbosity:         2

SHEEP2:
  notebook:      DCGAN/02-WGANGP-Draw-me-a-sheep.ipynb
  overrides:
    scale:                 default
    latent_dim:            default
    epochs:                default
    batch_size:            default
    num_img:               default
    fit_verbosity:         2

#
# ------------ DRL
#
# DRL1:
#   notebook:      DRL/FIDLE_DQNfromScratch.ipynb

# DRL2:
#   notebook:      DRL/FIDLE_rl_baselines_zoo.ipynb

#
# ------------ Misc
#
ACTF1:
  notebook:      Misc/Activation-Functions.ipynb

NP1:
  notebook:      Misc/Numpy.ipynb

SCRATCH1:
  notebook:      Misc/Scratchbook.ipynb

TSB1:
  notebook:      Misc/Using-Tensorboard.ipynb
