config:
  version: '1.0'
  output_tag: ==done==
  save_figs: true
LINR1:
  notebook_dir: LinearReg
  notebook_src: 01-Linear-Regression.ipynb
  notebook_out: default
GRAD1:
  notebook_dir: LinearReg
  notebook_src: 02-Gradient-descent.ipynb
  notebook_out: default
POLR1:
  notebook_dir: LinearReg
  notebook_src: 03-Polynomial-Regression.ipynb
  notebook_out: default
LOGR1:
  notebook_dir: LinearReg
  notebook_src: 04-Logistic-Regression.ipynb
  notebook_out: default
PER57:
  notebook_dir: IRIS
  notebook_src: 01-Simple-Perceptron.ipynb
  notebook_out: default
BHPD1:
  notebook_dir: BHPD
  notebook_src: 01-DNN-Regression.ipynb
  notebook_out: default
BHPD2:
  notebook_dir: BHPD
  notebook_src: 02-DNN-Regression-Premium.ipynb
  notebook_out: default
MNIST1:
  notebook_dir: MNIST
  notebook_src: 01-DNN-MNIST.ipynb
  notebook_out: default
GTSRB1:
  notebook_dir: GTSRB
  notebook_src: 01-Preparation-of-data.ipynb
  notebook_out: default
  overrides:
    scale: default
    output_dir: default
GTSRB2:
  notebook_dir: GTSRB
  notebook_src: 02-First-convolutions.ipynb
  notebook_out: default
  overrides:
    run_dir: default
    dataset_name: default
    batch_size: default
    epochs: default
    scale: default
GTSRB3:
  notebook_dir: GTSRB
  notebook_src: 03-Tracking-and-visualizing.ipynb
  notebook_out: default
  overrides:
    run_dir: default
    dataset_name: default
    batch_size: default
    epochs: default
    scale: default
GTSRB4:
  notebook_dir: GTSRB
  notebook_src: 04-Data-augmentation.ipynb
  notebook_out: default
  overrides:
    run_dir: default
    dataset_name: default
    batch_size: default
    epochs: default
    scale: default
GTSRB5:
  notebook_dir: GTSRB
  notebook_src: 05-Full-convolutions.ipynb
  notebook_out: default
  overrides:
    run_dir: default
    datasets: default
    models: default
    batch_size: default
    epochs: default
    scale: default
    with_datagen: default
    verbose: default
GTSRB6:
  notebook_dir: GTSRB
  notebook_src: 06-Notebook-as-a-batch.ipynb
  notebook_out: default
GTSRB7:
  notebook_dir: GTSRB
  notebook_src: 07-Show-report.ipynb
  notebook_out: default
  overrides:
    run_dir: default
    report_dir: default
GTSRB10:
  notebook_dir: GTSRB
  notebook_src: batch_oar.sh
  notebook_out: default
GTSRB11:
  notebook_dir: GTSRB
  notebook_src: batch_slurm.sh
  notebook_out: default
IMDB1:
  notebook_dir: IMDB
  notebook_src: 01-Embedding-Keras.ipynb
  notebook_out: default
IMDB2:
  notebook_dir: IMDB
  notebook_src: 02-Prediction.ipynb
  notebook_out: default
IMDB3:
  notebook_dir: IMDB
  notebook_src: 03-LSTM-Keras.ipynb
  notebook_out: default
SYNOP1:
  notebook_dir: SYNOP
  notebook_src: 01-Preparation-of-data.ipynb
  notebook_out: default
SYNOP2:
  notebook_dir: SYNOP
  notebook_src: 02-First-predictions.ipynb
  notebook_out: default
  overrides:
    scale: default
    train_prop: default
    sequence_len: default
    batch_size: default
    epochs: default
SYNOP3:
  notebook_dir: SYNOP
  notebook_src: 03-12h-predictions.ipynb
  notebook_out: default
  overrides:
    iterations: default
    scale: default
    train_prop: default
    sequence_len: default
    batch_size: default
    epochs: default
AE1:
  notebook_dir: AE
  notebook_src: 01-AE-with-MNIST.ipynb
  notebook_out: default
AE2:
  notebook_dir: AE
  notebook_src: 02-AE-with-MNIST-post.ipynb
  notebook_out: default
VAE1:
  notebook_dir: VAE
  notebook_src: 01-VAE-with-MNIST.ipynb
  notebook_out: default
  overrides:
    run_dir: default
    scale: default
    latent_dim: default
    r_loss_factor: default
    batch_size: default
    epochs: default
VAE2:
  notebook_dir: VAE
  notebook_src: 02-VAE-with-MNIST-post.ipynb
  notebook_out: default
  overrides:
    run_dir: default
VAE5:
  notebook_dir: VAE
  notebook_src: 05-About-CelebA.ipynb
  notebook_out: default
VAE6:
  notebook_dir: VAE
  notebook_src: 06-Prepare-CelebA-datasets.ipynb
  notebook_out: default
  overrides:
    scale: default
    image_size: default
    output_dir: default
VAE7:
  notebook_dir: VAE
  notebook_src: 07-Check-CelebA.ipynb
  notebook_out: default
  overrides:
    image_size: default
    enhanced_dir: default
VAE8:
  notebook_dir: VAE
  notebook_src: 08-VAE-with-CelebA.ipynb
  notebook_out: default
  overrides:
    run_dir: default
    scale: default
    image_size: default
    enhanced_dir: default
    latent_dim: default
    r_loss_factor: default
    batch_size: default
    epochs: default
VAE9:
  notebook_dir: VAE
  notebook_src: 09-VAE-withCelebA-post.ipynb
  notebook_out: default
  overrides:
    run_dir: default
    scale: default
    image_size: default
    enhanced_dir: default
VAE10:
  notebook_dir: VAE
  notebook_src: batch_slurm.sh
  notebook_out: default
ACTF1:
  notebook_dir: Misc
  notebook_src: Activation-Functions.ipynb
  notebook_out: default
NP1:
  notebook_dir: Misc
  notebook_src: Numpy.ipynb
  notebook_out: default
TSB1:
  notebook_dir: Misc
  notebook_src: Using-Tensorboard.ipynb
  notebook_out: default
